In [3]:
import tensorflow as tf


2023-12-28 19:23:18.065068: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-28 19:23:18.213638: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-28 19:23:18.213692: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-28 19:23:18.215744: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-28 19:23:18.233643: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-28 19:23:18.236779: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [51]:
numbers = [10, 55,23, -23, 57, -78, -57, 34, 106, 67]

In [52]:
df = tf.data.Dataset.from_tensor_slices(numbers)
df


<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [53]:
for sales in df:
  print(sales.numpy())

10
55
23
-23
57
-78
-57
34
106
67


In [54]:
for sales in df.take(3):
  print(sales.numpy())

10
55
23


In [55]:
df = df.map(lambda x: x*83)
for sales in df.as_numpy_iterator():
  print(sales)

830
4565
1909
-1909
4731
-6474
-4731
2822
8798
5561


In [56]:
df = df.shuffle(3)
for sales in df.as_numpy_iterator():
  print(sales)

830
-1909
1909
4731
-6474
4565
-4731
8798
2822
5561


In [57]:
for sales in df.batch(3):
  print(sales.numpy())

[ 830 1909 4731]
[-6474 -1909 -4731]
[4565 8798 5561]
[2822]


In [58]:
df = tf.data.Dataset.from_tensor_slices(numbers)
df = df.filter(lambda x: x>0).map(lambda y: y*83).shuffle(2).batch(3)
for sales in df.as_numpy_iterator():
  print(sales)

[4565 1909  830]
[2822 8798 4731]
[5561]


In [9]:
image_ds = tf.data.Dataset.list_files("vehicle/*/*", shuffle=False)
for file in image_ds.take(3):
    print(file.numpy())

b'vehicle/cars/3.jpg'
b'vehicle/cars/4.jpg'
b'vehicle/cars/5.png'


In [13]:
img_ds=image_ds.shuffle(80)


for file in image_ds.take(5):
    print(file.numpy())


b'vehicle/cars/3.jpg'
b'vehicle/cars/4.jpg'
b'vehicle/cars/5.png'
b'vehicle/plane/1.jpg'
b'vehicle/plane/2.jpg'


In [15]:
image_count=len(image_ds)
image_count

5

In [16]:
train_size = int(image_count*0.8)
train_ds=image_ds.take(train_size)
test_ds=image_ds.skip(train_size)


In [17]:

def get_label(file_path):
  import os
  return tf.strings.split(file_path,os.path.sep)[-2]

In [18]:
for i in train_ds.take(4):
  print(i.numpy())

b'vehicle/cars/3.jpg'
b'vehicle/cars/4.jpg'
b'vehicle/cars/5.png'
b'vehicle/plane/1.jpg'


In [19]:
for label in train_ds.map(get_label):
  print(label)

tf.Tensor(b'cars', shape=(), dtype=string)
tf.Tensor(b'cars', shape=(), dtype=string)
tf.Tensor(b'cars', shape=(), dtype=string)
tf.Tensor(b'plane', shape=(), dtype=string)


In [21]:
def process_image(file_path):
    
    label=get_label(file_path)

    
    img=tf.io.read_file(file_path)
    img=tf.io.image.decode_jpeg(img)
    img=tf.io.image.resize(img,(128,128))

    return img,label


In [27]:
import tensorflow as tf

# ... your code defining train_ds and process_image ...

for img, label in train_ds.map(process_image).take(2):
    print("image: ", img)
    print("label: ", label)










































































































































































































































































































































































































AttributeError: in user code:

    File "/tmp/ipykernel_5717/4252724421.py", line 7, in process_image  *
        img=tf.io.image.decode_jpeg(img)

    AttributeError: module 'tensorflow._api.v2.io' has no attribute 'image'
